version: '3.8'

services:
  app:
    image: ghcr.io/lrconsultoria/php-swoole:8.3-alpine
    container_name: laravel-swoole
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www
      - ./configs/php-swoole-local.ini:/usr/local/etc/php/conf.d/php-swoole-local.ini
    environment:
      APP_ENV: local
      DB_HOST: database
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password
      REDIS_HOST: redis
      OCTANE_SERVER: swoole
    networks:
      - laravel
    depends_on:
      - database
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: mysql:8.0
    container_name: laravel-swoole-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    container_name: laravel-swoole-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel
    command: redis-server --appendonly yes

  # Queue Worker separado para Swoole
  queue:
    image: ghcr.io/lrconsultoria/php-base:8.3-alpine
    container_name: laravel-swoole-queue
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: php artisan queue:work --verbose --tries=3 --timeout=90 --memory=512
    environment:
      APP_ENV: local
      DB_HOST: database
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password
      REDIS_HOST: redis
    networks:
      - laravel
    depends_on:
      - database
      - redis
    restart: unless-stopped

  # Horizon para gerenciamento de filas (opcional)
  horizon:
    image: ghcr.io/lrconsultoria/php-base:8.3-alpine
    container_name: laravel-horizon
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: php artisan horizon
    environment:
      APP_ENV: local
      DB_HOST: database
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password
      REDIS_HOST: redis
    networks:
      - laravel
    depends_on:
      - database
      - redis
    restart: unless-stopped

  # Nginx como proxy reverso (opcional para SSL/Load Balancing)
  nginx:
    image: nginx:alpine
    container_name: laravel-swoole-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/swoole-proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

volumes:
  mysql_data:
  redis_data:

networks:
  laravel:
    driver: bridge
